<!DOCTYPE html>
<html>
    <head>
        <title> Demo | Public Key Encryption  </title>
        <meta http-equiv = "Content-Type" content = "text/html; charset = UTF-8">
        <script type = "text/javascript" src = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"> </script>
        <script type = "text/javascript" src = "./js/main.js"> </script>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous">
        <style>
            body {
                padding: 25px 0px;
            }
            .encrypted-area, .decrypted-area {
                display: none;
                padding: 20px 0px;
            }
            .decrypted-message {
                padding: 10px;
                background-color: #D6CFC7;
                word-break: break-all;
            }

            .encrypted-message{
                padding: 10px;
                background-color: #BEBDB8;
                word-break: break-all;
            }
            label {
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <ul>
                        <li>Example for public key encryption and decryption with PHP methdods.</li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="decrypt-area">
                    <div class="form-group">
                        <label for="message_plain">Message to be encrypted</label>
                        <textarea id="message_plain" name="message", class="form-control" rows="8" cols=70>Text to encrypted and decrypted with PHP methods</textarea>
                    </div>
                    <div class="form-group">
                        <label for="pub_key">Key to be used</label>
                        <select id="pub_key" class="form-control">
                            <option value="new">Generate New Keys</option>
                            <option value="public-key.rsa.pub">public-key.rsa.pub</option> //generated by php methods
                            <option value="public-key.pem">public-key.pem</option> //generated by php methods
                            <option value="term-public.pem">term-public.pem</option> //generated from terminal
                        </select>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <button class="btn btn-primary ml-1" onClick="processTheMessageWithPhp();">Encrypt and Decrypt</button>
                        </div>
                    </div>
                    <div class="row encrypted-area">
                        <div class="col-md-8">
                            <label for="encrypted_message_contianer">Encrypted message</label>
                            <div id="encrypted_message_contianer" class="encrypted-message"></div>
                        </div>
                    </div>
                    <div class="row decrypted-area">
                        <div class="col-md-8">
                            <label for="decrypted_message_contianer">Dencrypted message</label>
                            <div id="decrypted_message_contianer" class="decrypted-message"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>